import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1789426482881 implements MigrationInterface {
    name = 'InitialSchema1789426482881'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "webhook_deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscriptionId" character varying NOT NULL, "eventType" character varying NOT NULL, "payload" jsonb NOT NULL, "statusCode" integer, "attempt" integer NOT NULL, "deliveredAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_535dd409947fb6d8fc6dfc0112a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "webhook_subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "url" character varying NOT NULL, "secret" character varying NOT NULL, "eventTypes" text array NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "revokedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_bf631ae77d39849d599817fb6f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usage_counters" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "metric" character varying NOT NULL, "period" character varying NOT NULL, "count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_fb39db314fa8fc2b6653f2f4e31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_94b3e8d411c2f29c7c44b62c86" ON "usage_counters" ("tenantId", "metric", "period") `);
        await queryRunner.query(`CREATE TABLE "tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "plan" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_53be67a04681c66b87ee27c9321" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "refreshTokenHash" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "revokedAt" TIMESTAMP, CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_57de40bc620f456c7311aa3a1e" ON "sessions" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b08788ca45cbd90f0bd96c2f07" ON "sessions" ("refreshTokenHash") `);
        await queryRunner.query(`CREATE TYPE "public"."role_assignments_role_enum" AS ENUM('owner', 'admin', 'member')`);
        await queryRunner.query(`CREATE TABLE "role_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "tenantId" character varying NOT NULL, "role" "public"."role_assignments_role_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fc2df9835ac1d2a34839f113783" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "idempotency_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "idempotencyKey" character varying NOT NULL, "requestPath" character varying NOT NULL, "responseStatus" integer NOT NULL, "responseBody" jsonb NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fbc986f7952126e5e111ec9b4a6" UNIQUE ("idempotencyKey"), CONSTRAINT "PK_9ae4e93699362b0d4e3da3dd1c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "storageKey" character varying NOT NULL, "originalFilename" character varying NOT NULL, "mimeType" character varying NOT NULL, "sizeBytes" integer NOT NULL, "uploadedBy" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6950622bb9b2204f7753d46bf43" UNIQUE ("storageKey"), CONSTRAINT "PK_17d6bda4e953aace5de8a299e34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "feature_flags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "flagKey" character varying NOT NULL, "enabled" boolean NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_db657d344e9caacfc9d5cf8bbac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6b25afda11a1352a98659fb480" ON "feature_flags" ("tenantId", "flagKey") `);
        await queryRunner.query(`CREATE TABLE "consent_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "tenantId" character varying NOT NULL, "consentType" character varying NOT NULL, "version" character varying NOT NULL, "grantedAt" TIMESTAMP WITH TIME ZONE, "revokedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_030be152eaa44998166470b2ccc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dead_letter_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "originalEvent" character varying NOT NULL, "payload" jsonb NOT NULL, "failureReason" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "retriedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_ed3e9080458f823199695dd7a55" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "stripeCustomerId" character varying NOT NULL, "stripeSubscriptionId" character varying NOT NULL, "plan" character varying NOT NULL, "status" character varying NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying, "tenantId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c58f7e88c286e5e3478960a998" ON "users" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "audit_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventName" character varying NOT NULL, "actorId" uuid, "tenantId" uuid, "payload" jsonb NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_6b1623bcad4d04530b76548d619" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "keyHash" character varying NOT NULL, "scopes" text array NOT NULL, "label" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "revokedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_df3b25181df0b4b59bd93f16e10" UNIQUE ("keyHash"), CONSTRAINT "PK_5c8a79801b44bd27b79228e1dad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "category" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'draft', "isPremium" boolean NOT NULL DEFAULT false, "fields" jsonb NOT NULL DEFAULT '[]', "createdBy" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_515948649ce0bbbe391de702ae5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cd885b46a142b9246c49df9e3c" ON "templates" ("tenantId", "status") `);
        await queryRunner.query(`CREATE TABLE "template_clauses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "templateId" character varying NOT NULL, "title" character varying NOT NULL, "body" text NOT NULL, "order" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bc3369d1a00469c382aa23b1899" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b2794009b01268a38435b47f59" ON "template_clauses" ("templateId") `);
        await queryRunner.query(`CREATE TABLE "reminders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" character varying NOT NULL, "reminderType" character varying NOT NULL, "recipientUserId" uuid, "recipientEmail" character varying, "scheduledFor" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "sentAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_38715fec7f634b72c6cf7ea4893" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_176a13688648e700328c7924aa" ON "reminders" ("contractId") `);
        await queryRunner.query(`CREATE INDEX "IDX_07a61777b6d3e0e21b8837fd31" ON "reminders" ("tenantId", "status") `);
        await queryRunner.query(`CREATE TABLE "negotiation_role_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" character varying NOT NULL, "userId" character varying NOT NULL, "role" character varying NOT NULL, "assignedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eb0eaf7587e3443619cf6d25a53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5c3062d2f88d7d959ee4d209e1" ON "negotiation_role_assignments" ("tenantId", "contractId", "userId") `);
        await queryRunner.query(`CREATE TABLE "approval_workflows" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "stages" integer NOT NULL DEFAULT '1', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f326145fd927565de30b360264b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4e89284a3030e5c63b3ee2879e" ON "approval_workflows" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "approval_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" character varying NOT NULL, "approverId" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "reason" text, "requestedAt" TIMESTAMP NOT NULL DEFAULT now(), "decidedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_484806bb8ff331b851fc75973c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4113651a4b0fde8052ca8a1e73" ON "approval_requests" ("tenantId", "contractId") `);
        await queryRunner.query(`CREATE TABLE "integration_connections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "integration" character varying NOT NULL, "enabled" boolean NOT NULL DEFAULT false, "syncUrl" character varying, "connectedAt" TIMESTAMP WITH TIME ZONE, "lastSyncedAt" TIMESTAMP WITH TIME ZONE, "lastSyncStatus" character varying NOT NULL DEFAULT 'idle', "lastSyncError" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b1ec518bfa5fa7404045412de2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_10361001ccf89cc2f0ade3e4bf" ON "integration_connections" ("tenantId", "integration") `);
        await queryRunner.query(`CREATE TABLE "signature_envelopes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" character varying NOT NULL, "fileId" character varying NOT NULL, "provider" character varying NOT NULL, "envelopeId" character varying NOT NULL, "signerEmail" character varying NOT NULL, "signerName" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'sent', "declineReason" text, "requestedAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6423640845eb5e4ef2fae0229ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4c2dad7560c326a06bffa2f56a" ON "signature_envelopes" ("envelopeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6cd16a18d07369cad8204663db" ON "signature_envelopes" ("tenantId", "contractId") `);
        await queryRunner.query(`CREATE TABLE "contracts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "templateId" uuid, "name" character varying NOT NULL, "description" text, "status" character varying NOT NULL DEFAULT 'draft', "createdBy" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2c7b8f3a7b1acdd49497d83d0fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f61a0165387c746826f9de41b3" ON "contracts" ("tenantId", "status") `);
        await queryRunner.query(`CREATE TABLE "contract_versions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" character varying NOT NULL, "versionNumber" integer NOT NULL, "fileId" character varying NOT NULL, "createdBy" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d975932f14e4d73be73188e295f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee6553ba079c54e9a659e0c756" ON "contract_versions" ("tenantId", "contractId") `);
        await queryRunner.query(`CREATE TABLE "compliance_trail_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" character varying NOT NULL, "eventName" character varying NOT NULL, "payload" jsonb NOT NULL, "recordedAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_6fea597de8a906dd625868dee1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_41f95b9815420b2fa5e2ccbbe7" ON "compliance_trail_entries" ("tenantId", "contractId") `);
        await queryRunner.query(`CREATE TABLE "compliance_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" uuid, "generatedBy" character varying NOT NULL, "entries" jsonb NOT NULL, "generatedAt" TIMESTAMP NOT NULL DEFAULT now(), "exportedFormat" character varying, "exportedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_eb94c451e8b0c8df6e4d64535a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_72303d6c7112362598198d02de" ON "compliance_reports" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "tenant_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "metric" character varying NOT NULL, "value" double precision NOT NULL DEFAULT '0', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_44a6bd4a9df35bc3e425470bfd1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c371168a49f27bab1cd1fb579a" ON "tenant_metrics" ("tenantId", "metric") `);
        await queryRunner.query(`CREATE TABLE "negotiation_timings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" character varying NOT NULL, "enteredNegotiationAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ed323586f27941ffe123f14a12b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_88f21a001d9afc3160a7e641e4" ON "negotiation_timings" ("tenantId", "contractId") `);
        await queryRunner.query(`CREATE TABLE "analytics_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "generatedBy" character varying NOT NULL, "tier" character varying NOT NULL, "metrics" jsonb NOT NULL, "generatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f1eb49d61068f2aeb3373e75ee6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f57f0104379479e1d9d857e51e" ON "analytics_reports" ("tenantId") `);
        await queryRunner.query(`CREATE TABLE "contract_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" character varying NOT NULL, "authorId" character varying NOT NULL, "body" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fa63b09bc9f5081e3c612e4c131" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f80859f494610efe4c6c97b713" ON "contract_comments" ("tenantId", "contractId") `);
        await queryRunner.query(`CREATE TABLE "contract_access_grants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" character varying NOT NULL, "userId" character varying NOT NULL, "permission" character varying NOT NULL, "grantedBy" character varying NOT NULL, "grantedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1042446b7306708f34295d56c18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_69f2ecb15500001a5b02503792" ON "contract_access_grants" ("tenantId", "contractId", "userId") `);
        await queryRunner.query(`CREATE TABLE "collaboration_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" character varying NOT NULL, "userId" character varying NOT NULL, "startedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_161c36edc6ac54f8cb7b6d070c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f891b8938ddf80f34336e7ef3b" ON "collaboration_sessions" ("tenantId", "contractId") `);
        await queryRunner.query(`CREATE TABLE "collaboration_invites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "contractId" character varying NOT NULL, "invitedEmail" character varying NOT NULL, "permission" character varying NOT NULL, "invitedBy" character varying NOT NULL, "invitedAt" TIMESTAMP NOT NULL DEFAULT now(), "resolvedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_74a1d578c7052ad82269099304b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4c55212926787d042c5a24a15e" ON "collaboration_invites" ("tenantId", "invitedEmail") `);
        await queryRunner.query(`CREATE TABLE "access_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" character varying NOT NULL, "defaultPermission" character varying NOT NULL DEFAULT 'view', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_93705ea815f89343d7bf80cd60e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ccf236accf1c94bf7b4cc77d89" ON "access_policies" ("tenantId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_ccf236accf1c94bf7b4cc77d89"`);
        await queryRunner.query(`DROP TABLE "access_policies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c55212926787d042c5a24a15e"`);
        await queryRunner.query(`DROP TABLE "collaboration_invites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f891b8938ddf80f34336e7ef3b"`);
        await queryRunner.query(`DROP TABLE "collaboration_sessions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69f2ecb15500001a5b02503792"`);
        await queryRunner.query(`DROP TABLE "contract_access_grants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f80859f494610efe4c6c97b713"`);
        await queryRunner.query(`DROP TABLE "contract_comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f57f0104379479e1d9d857e51e"`);
        await queryRunner.query(`DROP TABLE "analytics_reports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88f21a001d9afc3160a7e641e4"`);
        await queryRunner.query(`DROP TABLE "negotiation_timings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c371168a49f27bab1cd1fb579a"`);
        await queryRunner.query(`DROP TABLE "tenant_metrics"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72303d6c7112362598198d02de"`);
        await queryRunner.query(`DROP TABLE "compliance_reports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41f95b9815420b2fa5e2ccbbe7"`);
        await queryRunner.query(`DROP TABLE "compliance_trail_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee6553ba079c54e9a659e0c756"`);
        await queryRunner.query(`DROP TABLE "contract_versions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f61a0165387c746826f9de41b3"`);
        await queryRunner.query(`DROP TABLE "contracts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cd16a18d07369cad8204663db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c2dad7560c326a06bffa2f56a"`);
        await queryRunner.query(`DROP TABLE "signature_envelopes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_10361001ccf89cc2f0ade3e4bf"`);
        await queryRunner.query(`DROP TABLE "integration_connections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4113651a4b0fde8052ca8a1e73"`);
        await queryRunner.query(`DROP TABLE "approval_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e89284a3030e5c63b3ee2879e"`);
        await queryRunner.query(`DROP TABLE "approval_workflows"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c3062d2f88d7d959ee4d209e1"`);
        await queryRunner.query(`DROP TABLE "negotiation_role_assignments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07a61777b6d3e0e21b8837fd31"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_176a13688648e700328c7924aa"`);
        await queryRunner.query(`DROP TABLE "reminders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2794009b01268a38435b47f59"`);
        await queryRunner.query(`DROP TABLE "template_clauses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd885b46a142b9246c49df9e3c"`);
        await queryRunner.query(`DROP TABLE "templates"`);
        await queryRunner.query(`DROP TABLE "api_keys"`);
        await queryRunner.query(`DROP TABLE "audit_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c58f7e88c286e5e3478960a998"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TABLE "dead_letter_entries"`);
        await queryRunner.query(`DROP TABLE "consent_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b25afda11a1352a98659fb480"`);
        await queryRunner.query(`DROP TABLE "feature_flags"`);
        await queryRunner.query(`DROP TABLE "file_records"`);
        await queryRunner.query(`DROP TABLE "idempotency_records"`);
        await queryRunner.query(`DROP TABLE "role_assignments"`);
        await queryRunner.query(`DROP TYPE "public"."role_assignments_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b08788ca45cbd90f0bd96c2f07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57de40bc620f456c7311aa3a1e"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94b3e8d411c2f29c7c44b62c86"`);
        await queryRunner.query(`DROP TABLE "usage_counters"`);
        await queryRunner.query(`DROP TABLE "webhook_subscriptions"`);
        await queryRunner.query(`DROP TABLE "webhook_deliveries"`);
    }

}
